package sweda.cnpc_immersiveboss.client;

import com.goodbird.cnpcgeckoaddon.entity.EntityCustomModel;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.math.Axis;
import net.minecraft.client.Minecraft;
import net.minecraft.client.player.AbstractClientPlayer;
import net.minecraft.client.model.HumanoidArmorModel;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.Sheets;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.client.Camera;
import net.minecraft.client.CameraType;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.HumanoidArm;
import net.minecraft.world.phys.Vec3;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.DyeableLeatherItem;
import net.minecraft.world.item.ItemDisplayContext;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.armortrim.ArmorTrim;
import net.minecraft.client.model.Model;
import net.minecraftforge.client.ForgeHooksClient;
import org.joml.Matrix4f;
import org.joml.Quaternionf;
import org.joml.Vector3f;
import software.bernie.geckolib.cache.GeckoLibCache;
import software.bernie.geckolib.cache.object.BakedGeoModel;
import software.bernie.geckolib.cache.object.GeoBone;
import sweda.cnpc_immersiveboss.mixin.CameraInvoker;
import sweda.cnpc_immersiveboss.throwing.StruggleMode;

import java.util.Map;
import java.util.ArrayDeque;
import java.util.Deque;
import java.util.Locale;
import java.util.concurrent.ConcurrentHashMap;

/** Client-side state for the embedded player puppet and its throw cameras. */
public final class ThrowClientState {
    /** Standard camera bones generated by the Blockbench helper. */
    public static final String CAMERA_ROOT = "camera_root";
    public static final String CAMERA_SECOND_PERSON = "camera_second_person";
    public static final String CAMERA_THIRD_PERSON = "camera_third_person";
    private static final double FALLBACK_CAMERA_DISTANCE = 4.0D;
    private static final Map<Integer, ThrowView> BY_TARGET = new ConcurrentHashMap<>();
    private static final Map<Integer, CameraPoses> CAMERA_POSES = new ConcurrentHashMap<>();
    /** Baked vanilla armor geometry, split by classic/slim arm width. */
    private static final Map<Boolean, ArmorModels> ARMOR_MODELS = new ConcurrentHashMap<>();
    private static final ThreadLocal<Deque<RenderContext>> ACTIVE_RENDERS =
        ThreadLocal.withInitial(ArrayDeque::new);
    /** Base matrices let camera bones be converted from GeckoLib render space to NPC space. */
    private static final ThreadLocal<Deque<ModelRender>> ACTIVE_MODELS =
        ThreadLocal.withInitial(ArrayDeque::new);

    private ThrowClientState() {
    }

    public static void start(int sequence, int npcId, int targetId, long startTick,
                             int durationTicks, String cameraBone,
                             StruggleMode struggleMode, int difficulty) {
        ThrowView previous = BY_TARGET.get(targetId);
        if (previous != null && previous.sequence == sequence
            && previous.npcId == npcId && previous.targetId == targetId) {
            return;
        }
        BY_TARGET.put(targetId, new ThrowView(sequence, npcId, targetId, startTick,
            durationTicks, cameraBone == null || cameraBone.isEmpty()
                ? CAMERA_ROOT : cameraBone));
        CAMERA_POSES.remove(npcId);
        Minecraft minecraft = Minecraft.getInstance();
        if (minecraft.player != null && minecraft.player.getId() == targetId) {
            StruggleClientState.start(sequence, struggleMode, difficulty);
        }
    }

    public static void stop(int sequence, int targetId) {
        ThrowView current = BY_TARGET.get(targetId);
        if (current != null && current.sequence == sequence) {
            BY_TARGET.remove(targetId);
            CAMERA_POSES.remove(current.npcId);
            StruggleClientState.stop(sequence);
        }
    }

    public static boolean isActiveForNpc(int npcId) {
        for (ThrowView view : BY_TARGET.values()) {
            if (view.npcId == npcId) return true;
        }
        return false;
    }

    public static boolean isActiveForTarget(int targetId) {
        return BY_TARGET.containsKey(targetId);
    }

    public static void tick() {
        Minecraft minecraft = Minecraft.getInstance();
        if (minecraft.level == null) {
            clear();
            return;
        }
        long now = minecraft.level.getGameTime();
        BY_TARGET.entrySet().removeIf(entry -> {
            ThrowView view = entry.getValue();
            if (now - view.startTick < view.durationTicks + 5L) return false;
            CAMERA_POSES.remove(view.npcId);
            StruggleClientState.stop(view.sequence);
            return true;
        });
        StruggleClientState.tick();
    }

    public static void clear() {
        BY_TARGET.clear();
        CAMERA_POSES.clear();
        StruggleClientState.clear();
    }

    public static void beginRender(MultiBufferSource buffers, RenderType renderType) {
        if (buffers != null) ACTIVE_RENDERS.get().push(new RenderContext(buffers, renderType));
    }

    public static void endRender() {
        Deque<RenderContext> renders = ACTIVE_RENDERS.get();
        if (!renders.isEmpty()) {
            RenderContext context = renders.peek();
            // A BufferSource tracks the last requested RenderType. Re-select
            // the NPC type before leaving the bone so later GeckoLib layers
            // cannot inherit the victim skin batch.
            originalConsumer(context.buffers, context.renderType, null);
            renders.pop();
        }
        if (renders.isEmpty()) ACTIVE_RENDERS.remove();
    }

    /**
     * End a temporary victim-skin batch before GeckoLib renders layers or
     * child bones using the model's original consumer.
     */
    public static void restoreOriginalRender() {
        Deque<RenderContext> renders = ACTIVE_RENDERS.get();
        if (!renders.isEmpty()) {
            RenderContext context = renders.peek();
            originalConsumer(context.buffers, context.renderType, null);
        }
    }

    public static void beginModelRender(EntityCustomModel model, Matrix4f renderBase) {
        if (model != null && renderBase != null) {
            ACTIVE_MODELS.get().push(new ModelRender(model, new Matrix4f(renderBase)));
        }
    }

    public static void endModelRender(EntityCustomModel model) {
        Deque<ModelRender> models = ACTIVE_MODELS.get();
        if (!models.isEmpty() && models.peek().model == model) {
            models.pop();
        } else {
            models.removeIf(render -> render.model == model);
        }
        if (models.isEmpty()) ACTIVE_MODELS.remove();
    }

    private static boolean isVictimBone(EntityCustomModel model, GeoBone bone) {
        if (model == null || bone == null || model.modelResLoc == null) return false;
        BakedGeoModel baked = GeckoLibCache.getBakedModels().get(model.modelResLoc);
        if (baked == null) return false;
        GeoBone root = baked.getBone("victim_root").orElse(null);
        if (root == null) return false;

        // Use the actual baked subtree instead of only a name/parent walk.
        // This keeps similarly named NPC bones and malformed legacy parent
        // links from redirecting their vertices to the player's skin.
        Deque<GeoBone> pending = new ArrayDeque<>();
        pending.push(root);
        while (!pending.isEmpty()) {
            GeoBone current = pending.pop();
            if (current == bone) return true;
            for (GeoBone child : current.getChildBones()) {
                if (child != null) pending.push(child);
            }
        }
        return false;
    }

    public static VertexConsumer victimConsumer(EntityCustomModel model, GeoBone bone,
                                                MultiBufferSource buffers,
                                                RenderType renderType,
                                                VertexConsumer original) {
        if (!isVictimBone(model, bone) || model.owner == null) {
            return originalConsumer(buffers, renderType, original);
        }
        ThrowView view = viewForNpc(model.owner.getId());
        if (view == null) return originalConsumer(buffers, renderType, original);

        Minecraft minecraft = Minecraft.getInstance();
        if (minecraft.level == null) return originalConsumer(buffers, renderType, original);
        Entity target = findTarget(minecraft, view.targetId);
        if (!(target instanceof AbstractClientPlayer player)) {
            return originalConsumer(buffers, renderType, original);
        }
        ResourceLocation skin = player.getSkinTextureLocation();
        VertexConsumer skinConsumer = buffers.getBuffer(RenderType.entityTranslucent(skin));
        return remapPlayerUv(model, skinConsumer);
    }

    /**
     * Draws the equipment of the player represented by victim_root.  This is
     * called while GeckoLib has already applied the current bone and all of
     * its parents to the PoseStack, so animated rotations/scales are retained.
     */
    public static void renderEquipment(EntityCustomModel model, GeoBone bone,
                                       PoseStack poseStack, MultiBufferSource buffers,
                                       int packedLight, float partialTick) {
        if (model == null || bone == null || poseStack == null || buffers == null
            || model.owner == null || !isVictimBone(model, bone)) {
            return;
        }
        ThrowView view = viewForNpc(model.owner.getId());
        if (view == null) return;
        Minecraft minecraft = Minecraft.getInstance();
        if (minecraft.level == null) return;
        Entity target = findTarget(minecraft, view.targetId);
        if (!(target instanceof AbstractClientPlayer player)) return;

        String name = bone.getName();
        if (name == null) return;
        switch (name) {
            case "victim_head" -> {
                renderArmorPart(player, bone, EquipmentSlot.HEAD, ArmorPart.HEAD,
                    poseStack, buffers, packedLight, partialTick);
                renderArmorPart(player, bone, EquipmentSlot.HEAD, ArmorPart.HAT,
                    poseStack, buffers, packedLight, partialTick);
            }
            case "victim_body" -> {
                renderArmorPart(player, bone, EquipmentSlot.CHEST, ArmorPart.BODY,
                    poseStack, buffers, packedLight, partialTick);
                renderArmorPart(player, bone, EquipmentSlot.LEGS, ArmorPart.BODY,
                    poseStack, buffers, packedLight, partialTick);
            }
            case "victim_right_arm" -> renderArmorPart(player, bone, EquipmentSlot.CHEST,
                ArmorPart.RIGHT_ARM, poseStack, buffers, packedLight, partialTick);
            case "victim_left_arm" -> renderArmorPart(player, bone, EquipmentSlot.CHEST,
                ArmorPart.LEFT_ARM, poseStack, buffers, packedLight, partialTick);
            case "victim_right_leg" -> {
                renderArmorPart(player, bone, EquipmentSlot.LEGS, ArmorPart.RIGHT_LEG,
                    poseStack, buffers, packedLight, partialTick);
                renderArmorPart(player, bone, EquipmentSlot.FEET, ArmorPart.RIGHT_LEG,
                    poseStack, buffers, packedLight, partialTick);
            }
            case "victim_left_leg" -> {
                renderArmorPart(player, bone, EquipmentSlot.LEGS, ArmorPart.LEFT_LEG,
                    poseStack, buffers, packedLight, partialTick);
                renderArmorPart(player, bone, EquipmentSlot.FEET, ArmorPart.LEFT_LEG,
                    poseStack, buffers, packedLight, partialTick);
            }
            case "victim_right_item" -> renderHeldItem(player, bone, HumanoidArm.RIGHT,
                poseStack, buffers, packedLight);
            case "victim_left_item" -> renderHeldItem(player, bone, HumanoidArm.LEFT,
                poseStack, buffers, packedLight);
            default -> {
                // Other victim bones (camera/skin layers) do not carry equipment.
            }
        }
    }

    private static void renderHeldItem(AbstractClientPlayer player, GeoBone bone,
                                       HumanoidArm arm,
                                       PoseStack poseStack, MultiBufferSource buffers,
                                       int packedLight) {
        HumanoidArm mainArm = player.getMainArm();
        boolean right = arm == HumanoidArm.RIGHT;
        ItemStack stack = right == (mainArm == HumanoidArm.RIGHT)
            ? player.getMainHandItem() : player.getOffhandItem();
        if (stack.isEmpty()) return;

        Minecraft minecraft = Minecraft.getInstance();
        poseStack.pushPose();
        // GeoEntityRenderer has already applied this bone and all parent
        // transforms, then translated away from the pivot before invoking
        // renderRecursively. Translate back to the attachment pivot so the
        // item is anchored to the hand group; the pivot is part of the bone's
        // complete animated transform and must not be omitted.
        poseStack.translate(bone.getPivotX() / 16.0F, bone.getPivotY() / 16.0F,
            bone.getPivotZ() / 16.0F);
        // Keep the grip adjustment local to the item group so its parent arm
        // and all animated position/rotation/scale remain intact.
        poseStack.scale(0.7F, 0.7F, 0.7F);
        poseStack.mulPose(Axis.XP.rotationDegrees(-90.0F));
        poseStack.mulPose(Axis.YP.rotationDegrees(180.0F));
        boolean left = arm == HumanoidArm.LEFT;
        poseStack.translate((left ? -1.0F : 1.0F) / 16.0F, 0.125F, -0.625F);
        minecraft.getItemRenderer().renderStatic(player, stack,
            right ? ItemDisplayContext.THIRD_PERSON_RIGHT_HAND
                  : ItemDisplayContext.THIRD_PERSON_LEFT_HAND,
            left, poseStack, buffers, minecraft.level, packedLight,
            OverlayTexture.NO_OVERLAY, 0);
        poseStack.popPose();
    }

    private static void renderArmorPart(AbstractClientPlayer player, GeoBone bone,
                                        EquipmentSlot slot,
                                        ArmorPart part, PoseStack poseStack,
                                        MultiBufferSource buffers, int packedLight,
                                        float partialTick) {
        ItemStack stack = player.getItemBySlot(slot);
        if (!(stack.getItem() instanceof ArmorItem armor)
            || armor.getEquipmentSlot() != slot) return;

        ArmorModels models = armorModels(player);
        HumanoidArmorModel<AbstractClientPlayer> baked =
            slot == EquipmentSlot.LEGS ? models.inner : models.outer;
        Model armorModel = ForgeHooksClient.getArmorModel(player, stack, slot, baked);
        if (!(armorModel instanceof net.minecraft.client.model.HumanoidModel<?> humanoid)) {
            // Non-humanoid custom armor models cannot be split by victim bone;
            // vanilla armor remains fully supported and is the common case.
            return;
        }
        ModelPart modelPart = part.modelPart(humanoid);
        if (modelPart == null) return;

        poseStack.pushPose();
        // renderRecursively has translated away from the bone's pivot.
        // Return to the actual joint, including any authored rig offset,
        // then convert vanilla's X/Y axes to GeckoLib's render coordinates.
        poseStack.translate(bone.getPivotX() / 16.0F, bone.getPivotY() / 16.0F,
            bone.getPivotZ() / 16.0F);
        poseStack.scale(-1.0F, -1.0F, 1.0F);
        poseStack.translate(part.xOffset, 0.0F, 0.0F);
        float oldX = modelPart.x, oldY = modelPart.y, oldZ = modelPart.z;
        float oldXRot = modelPart.xRot, oldYRot = modelPart.yRot, oldZRot = modelPart.zRot;
        boolean oldVisible = modelPart.visible;
        // GeckoLib has already applied the complete bone transform.  Remove
        // HumanoidModel's baked joint transform so it is not applied twice.
        modelPart.x = modelPart.y = modelPart.z = 0.0F;
        modelPart.xRot = modelPart.yRot = modelPart.zRot = 0.0F;
        modelPart.visible = true;
        try {
            ResourceLocation texture = armorTexture(player, stack, armor, slot, null);
            float red = 1.0F, green = 1.0F, blue = 1.0F;
            if (armor instanceof DyeableLeatherItem dyeable) {
                int color = dyeable.getColor(stack);
                red = (color >> 16 & 255) / 255.0F;
                green = (color >> 8 & 255) / 255.0F;
                blue = (color & 255) / 255.0F;
            }
            VertexConsumer baseConsumer = buffers.getBuffer(RenderType.armorCutoutNoCull(texture));
            renderArmorModelPart(modelPart, poseStack, baseConsumer, packedLight, red, green, blue);
            if (armor instanceof DyeableLeatherItem) {
                ResourceLocation overlay = armorTexture(player, stack, armor, slot, "overlay");
                renderArmorModelPart(modelPart, poseStack,
                    buffers.getBuffer(RenderType.armorCutoutNoCull(overlay)), packedLight,
                    1.0F, 1.0F, 1.0F);
            }

            ArmorTrim.getTrim(player.level().registryAccess(), stack).ifPresent(trim -> {
                TextureAtlasSprite sprite = Minecraft.getInstance().getModelManager()
                    .getAtlas(Sheets.ARMOR_TRIMS_SHEET).getSprite(
                        slot == EquipmentSlot.LEGS
                            ? trim.innerTexture(armor.getMaterial())
                            : trim.outerTexture(armor.getMaterial()));
                renderArmorModelPart(modelPart, poseStack,
                    sprite.wrap(buffers.getBuffer(Sheets.armorTrimsSheet())),
                    packedLight, 1.0F, 1.0F, 1.0F);
            });
            if (stack.hasFoil()) {
                renderArmorModelPart(modelPart, poseStack,
                    buffers.getBuffer(RenderType.armorEntityGlint()), packedLight,
                    1.0F, 1.0F, 1.0F);
            }
        } finally {
            modelPart.x = oldX; modelPart.y = oldY; modelPart.z = oldZ;
            modelPart.xRot = oldXRot; modelPart.yRot = oldYRot; modelPart.zRot = oldZRot;
            modelPart.visible = oldVisible;
            poseStack.popPose();
        }
    }

    private static void renderArmorModelPart(ModelPart part, PoseStack poseStack,
                                             VertexConsumer consumer, int light,
                                             float red, float green, float blue) {
        part.render(poseStack, consumer, light, OverlayTexture.NO_OVERLAY,
            red, green, blue, 1.0F);
    }

    private static ResourceLocation armorTexture(AbstractClientPlayer player,
                                                 ItemStack stack, ArmorItem armor,
                                                 EquipmentSlot slot, String type) {
        String material = armor.getMaterial().getName();
        String domain = "minecraft";
        int separator = material.indexOf(':');
        if (separator >= 0) {
            domain = material.substring(0, separator);
            material = material.substring(separator + 1);
        }
        int layer = slot == EquipmentSlot.LEGS ? 2 : 1;
        String path = String.format(Locale.ROOT,
            "%s:textures/models/armor/%s_layer_%d%s.png", domain, material, layer,
            type == null ? "" : "_" + type);
        return new ResourceLocation(ForgeHooksClient.getArmorTexture(player, stack, path, slot, type));
    }

    private static ArmorModels armorModels(AbstractClientPlayer player) {
        boolean slim = "slim".equalsIgnoreCase(player.getModelName());
        return ARMOR_MODELS.computeIfAbsent(slim, key -> {
            Minecraft minecraft = Minecraft.getInstance();
            ModelPart inner = minecraft.getEntityModels().bakeLayer(
                key ? ModelLayers.PLAYER_SLIM_INNER_ARMOR : ModelLayers.PLAYER_INNER_ARMOR);
            ModelPart outer = minecraft.getEntityModels().bakeLayer(
                key ? ModelLayers.PLAYER_SLIM_OUTER_ARMOR : ModelLayers.PLAYER_OUTER_ARMOR);
            return new ArmorModels(new HumanoidArmorModel<>(inner),
                new HumanoidArmorModel<>(outer));
        });
    }

    /** Restore the model's own batch after another bone selected the skin batch. */
    private static VertexConsumer originalConsumer(MultiBufferSource buffers,
                                                   RenderType renderType,
                                                   VertexConsumer original) {
        if (buffers != null && renderType != null) return buffers.getBuffer(renderType);
        return original;
    }

    /**
     * GeckoLib normalizes model UVs using the Geo file's texture dimensions.
     * Player skins are always 64x64, so a shared 512x512 NPC model would
     * otherwise sample only a tiny region from the skin. Keep the remapping
     * scoped to victim bones and leave every other model/material untouched.
     */
    private static VertexConsumer remapPlayerUv(EntityCustomModel model,
                                                VertexConsumer consumer) {
        if (model.modelResLoc == null) return consumer;
        BakedGeoModel baked = GeckoLibCache.getBakedModels().get(model.modelResLoc);
        if (baked == null || baked.properties() == null) return consumer;

        double textureWidth = baked.properties().textureWidth();
        double textureHeight = baked.properties().textureHeight();
        if (!(textureWidth > 0.0D) || !(textureHeight > 0.0D)
            || !Double.isFinite(textureWidth) || !Double.isFinite(textureHeight)) {
            return consumer;
        }
        float scaleU = (float) (textureWidth / 64.0D);
        float scaleV = (float) (textureHeight / 64.0D);
        if (Math.abs(scaleU - 1.0F) < 0.0001F && Math.abs(scaleV - 1.0F) < 0.0001F) {
            return consumer;
        }
        return new PlayerSkinVertexConsumer(consumer, scaleU, scaleV);
    }

    private static Entity findTarget(Minecraft minecraft, int targetId) {
        Entity target = minecraft.level.getEntity(targetId);
        if (target != null) return target;
        if (minecraft.player != null && minecraft.player.getId() == targetId) {
            return minecraft.player;
        }
        for (AbstractClientPlayer player : minecraft.level.players()) {
            if (player.getId() == targetId) return player;
        }
        return null;
    }

    /** VertexConsumer decorator that changes only the diffuse UV coordinates. */
    private static final class PlayerSkinVertexConsumer implements VertexConsumer {
        private final VertexConsumer delegate;
        private final float scaleU;
        private final float scaleV;

        private PlayerSkinVertexConsumer(VertexConsumer delegate, float scaleU, float scaleV) {
            this.delegate = delegate;
            this.scaleU = scaleU;
            this.scaleV = scaleV;
        }

        @Override
        public VertexConsumer vertex(double x, double y, double z) {
            delegate.vertex(x, y, z);
            return this;
        }

        @Override
        public VertexConsumer color(int red, int green, int blue, int alpha) {
            delegate.color(red, green, blue, alpha);
            return this;
        }

        @Override
        public VertexConsumer uv(float u, float v) {
            delegate.uv(u * scaleU, v * scaleV);
            return this;
        }

        @Override
        public VertexConsumer overlayCoords(int u, int v) {
            delegate.overlayCoords(u, v);
            return this;
        }

        @Override
        public VertexConsumer uv2(int u, int v) {
            delegate.uv2(u, v);
            return this;
        }

        @Override
        public VertexConsumer normal(float x, float y, float z) {
            delegate.normal(x, y, z);
            return this;
        }

        @Override
        public void endVertex() {
            delegate.endVertex();
        }

        @Override
        public void defaultColor(int red, int green, int blue, int alpha) {
            delegate.defaultColor(red, green, blue, alpha);
        }

        @Override
        public void unsetDefaultColor() {
            delegate.unsetDefaultColor();
        }
    }

    public static VertexConsumer victimConsumer(EntityCustomModel model, GeoBone bone,
                                                VertexConsumer original) {
        Deque<RenderContext> stack = ACTIVE_RENDERS.get();
        RenderContext context = stack.peek();
        return context == null ? original
            : victimConsumer(model, bone, context.buffers, context.renderType, original);
    }

    public static void captureCamera(EntityCustomModel model, GeoBone bone,
                                     Matrix4f matrix, float partialTick) {
        if (model.owner == null) return;
        ThrowView view = viewForNpc(model.owner.getId());
        if (view == null || !isCameraBone(view, bone.getName())) return;

        Minecraft minecraft = Minecraft.getInstance();
        if (minecraft.gameRenderer == null) return;
        ModelRender render = activeModel(model);
        if (render == null) return;

        Matrix4f inverseBase = new Matrix4f(render.renderBase).invert();
        if (!inverseBase.isFinite()) return;
        // GeckoLib's matrix includes projection, view, entity, and model
        // transforms. Removing the render base leaves the NPC-relative bone
        // transform, matching OBBRenderCapture's coordinate convention.
        Matrix4f relative = inverseBase.mul(matrix);
        Vector3f pivot = new Vector3f(
            bone.getPivotX() / 16.0F,
            bone.getPivotY() / 16.0F,
            bone.getPivotZ() / 16.0F);
        Vector3f position = relative.transformPosition(pivot);
        Vec3 origin = model.owner.getPosition(partialTick);
        Vec3 worldPosition = origin.add(position.x, position.y, position.z);
        Quaternionf rotation = relative.getNormalizedRotation(new Quaternionf());
        CAMERA_POSES.compute(view.npcId, (id, poses) -> {
            CameraPoses current = poses == null ? CameraPoses.empty() : poses;
            String name = bone.getName();
            if (name.equals(view.cameraBone) || (CAMERA_ROOT.equals(name)
                && CAMERA_ROOT.equals(view.cameraBone))) {
                return current.withPrimary(new CameraPose(worldPosition, rotation));
            }
            if (CAMERA_SECOND_PERSON.equals(name)) {
                return current.withSecond(new CameraPose(worldPosition, rotation));
            }
            if (CAMERA_THIRD_PERSON.equals(name)) {
                return current.withThird(new CameraPose(worldPosition, rotation));
            }
            return current;
        });
    }

    public static void applyCamera(Camera camera) {
        Minecraft minecraft = Minecraft.getInstance();
        if (camera == null || minecraft.gameRenderer == null
            || camera != minecraft.gameRenderer.getMainCamera()
            || minecraft.player == null || camera.getEntity() != minecraft.player) {
            return;
        }
        ThrowView view = BY_TARGET.get(minecraft.player.getId());
        if (view == null) return;
        CameraPoses poses = CAMERA_POSES.get(view.npcId);
        if (poses == null || poses.primary == null) return;

        CameraPose pose = selectPose(minecraft.options.getCameraType(), poses);
        if (pose == null) return;

        ((CameraInvoker) (Object) camera).cnpc_immersiveboss$setPosition(pose.position);
        // Blockbench cameras look down their local -Z axis.
        Vector3f forward = new Vector3f(0, 0, -1).rotate(pose.rotation);
        float yaw = (float) Math.toDegrees(Math.atan2(-forward.x, forward.z));
        float pitch = (float) Math.toDegrees(Math.asin(-Math.max(-1.0F,
            Math.min(1.0F, forward.y))));
        ((CameraInvoker) (Object) camera).cnpc_immersiveboss$setRotation(yaw, pitch);
    }

    private static boolean isCameraBone(ThrowView view, String name) {
        return name != null && (name.equals(view.cameraBone)
            || CAMERA_SECOND_PERSON.equals(name)
            || CAMERA_THIRD_PERSON.equals(name));
    }

    private static CameraPose selectPose(CameraType type, CameraPoses poses) {
        if (type == CameraType.THIRD_PERSON_FRONT) {
            return poses.second != null ? poses.second : fallbackPose(poses.primary, true);
        }
        if (type == CameraType.THIRD_PERSON_BACK) {
            return poses.third != null ? poses.third : fallbackPose(poses.primary, false);
        }
        return poses.primary;
    }

    /**
     * Derives a missing external camera from the first-person camera. The
     * first-person forward vector is the model's local -Z direction. A front
     * camera is placed farther along that vector and looks back at the player;
     * a back camera is placed behind the player and keeps the same heading.
     */
    private static CameraPose fallbackPose(CameraPose primary, boolean front) {
        Vector3f forward = new Vector3f(0, 0, -1).rotate(primary.rotation);
        Vec3 offset = new Vec3(forward.x, forward.y, forward.z)
            .scale(front ? FALLBACK_CAMERA_DISTANCE : -FALLBACK_CAMERA_DISTANCE);
        Quaternionf rotation = new Quaternionf(primary.rotation);
        if (front) rotation.rotateY((float) Math.PI);
        return new CameraPose(primary.position.add(offset), rotation);
    }

    private static ThrowView viewForNpc(int npcId) {
        for (ThrowView view : BY_TARGET.values()) {
            if (view.npcId == npcId) return view;
        }
        return null;
    }

    private static ModelRender activeModel(EntityCustomModel model) {
        for (ModelRender render : ACTIVE_MODELS.get()) {
            if (render.model == model) return render;
        }
        return null;
    }

    private record ThrowView(int sequence, int npcId, int targetId, long startTick,
                             int durationTicks, String cameraBone) {
    }

    private record CameraPoses(CameraPose primary, CameraPose second, CameraPose third) {
        private static CameraPoses empty() {
            return new CameraPoses(null, null, null);
        }

        private CameraPoses withPrimary(CameraPose pose) {
            return new CameraPoses(pose, second, third);
        }

        private CameraPoses withSecond(CameraPose pose) {
            return new CameraPoses(primary, pose, third);
        }

        private CameraPoses withThird(CameraPose pose) {
            return new CameraPoses(primary, second, pose);
        }
    }

    private record CameraPose(Vec3 position, Quaternionf rotation) {
    }

    private record ModelRender(EntityCustomModel model, Matrix4f renderBase) {
    }

    private record RenderContext(MultiBufferSource buffers, RenderType renderType) {
    }

    private enum ArmorPart {
        HEAD(0.0F),
        HAT(0.0F),
        BODY(0.0F),
        // The rig's right arm is on Blockbench +X. Relative to its shoulder,
        // its cube spans -1..3, while vanilla's right armor spans -3..1.
        // Apply this correction before the X-axis conversion (left mirrors it).
        RIGHT_ARM(2.0F / 16.0F),
        LEFT_ARM(-2.0F / 16.0F),
        RIGHT_LEG(0.0F),
        LEFT_LEG(0.0F);

        private final float xOffset;
        ArmorPart(float xOffset) {
            this.xOffset = xOffset;
        }

        private ModelPart modelPart(net.minecraft.client.model.HumanoidModel<?> model) {
            return switch (this) {
                case HEAD -> model.head;
                case HAT -> model.hat;
                case BODY -> model.body;
                case RIGHT_ARM -> model.rightArm;
                case LEFT_ARM -> model.leftArm;
                case RIGHT_LEG -> model.rightLeg;
                case LEFT_LEG -> model.leftLeg;
            };
        }
    }

    private record ArmorModels(HumanoidArmorModel<AbstractClientPlayer> inner,
                               HumanoidArmorModel<AbstractClientPlayer> outer) {
    }
}
